#수정 시 즉시 반영됨 | Changes are reflected immediately

VANILLA_OSU = 1500
VANILLA_TAIKO = 0
VANILLA_CATCH = 0
VANILLA_MANIA = 0

RELAX_OSU = 3500
RELAX_TAIKO = 0
RELAX_CATCH = 0
RELAX_MANIA = 0  # unused

AUTOPILOT_OSU = 3500
AUTOPILOT_TAIKO = 0  # unused
AUTOPILOT_CATCH = 0  # unused
AUTOPILOT_MANIA = 0  # unused

def modeToPP(mode: int) -> int: return [VANILLA_OSU, VANILLA_TAIKO, VANILLA_CATCH, VANILLA_MANIA, RELAX_OSU, RELAX_TAIKO, RELAX_CATCH, RELAX_MANIA, AUTOPILOT_OSU, AUTOPILOT_TAIKO, AUTOPILOT_CATCH, AUTOPILOT_MANIA][mode]